inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Include:
    - 'lib/*'

Metrics/LineLength:
  Include:
    - 'lib/*'

Metrics/MethodLength:
  Max: 25

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ColonMethodCall:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/MutableConstant:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/Not:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/SpaceBeforeBlockBraces:
  Enabled: false
